language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - go test -covermode=count -coverprofile=profile.cov
    - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=profile.cov
